// Don't Come Home // Incident 02:13
// Story data — all scene definitions, endings, and branching logic
// Hidden variables: trust, danger, memory

/* jshint esversion: 6 */
/* global STORY */

const STORY = {

  scenes: {

    start: {
      id: "start",
      title: "02:13",
      text: [
        "Your phone lights up.",
        "One message. Unknown number.",
        "",
        "<em>Don't come home. Something inside the apartment learned my voice.</em>",
        "",
        "The timestamp reads 2:13 AM.",
        "You were supposed to be home two hours ago.",
      ],
      returnText: [
        "Your phone lights up.",
        "Unknown number.",
        "",
        "<em>Don't come home. Something inside the apartment learned my voice.</em>",
        "",
        "You've seen this before.",
        "You don't remember why.",
      ],
      choices: [
        { text: "Call the number back.", next: "call_back" },
        { text: "Go home anyway.", next: "go_home", effects: { danger: 1 } },
        { text: "Reply: \"Who is this?\"", next: "wait" },
      ],
    },

    wait: {
      id: "wait",
      title: "02:17",
      text: [
        "No reply for four minutes.",
        "Then, one more message from the same number:",
        "",
        "<em>It knows your name.</em>",
        "",
        "Your roommate's name is in your contacts.",
        "Their name is also in your mouth right now, silently.",
      ],
      choices: [
        { text: "Reply: \"Where are you right now?\"", next: "trace" },
        { text: "Power off your phone. Don't engage.", next: "ignore" },
        { text: "Go home anyway.", next: "go_home", effects: { danger: 1 } },
      ],
    },

    call_back: {
      id: "call_back",
      title: "02:15",
      text: [
        "The line rings once.",
        "Someone picks up.",
        "",
        "The voice is theirs. Perfectly.",
        "The cadence, the slight hesitation before sentences—all of it.",
        "",
        "<em>\"You should come home. I'm scared.\"</em>",
        "",
        "There's no background noise.",
        "None at all.",
      ],
      choices: [
        { text: "Ask them to prove who they are.", next: "proof", effects: { memory: 1 } },
        { text: "Believe them. Agree to come home.", next: "trust_voice", effects: { trust: 2 } },
        { text: "Hang up. Call the police instead.", next: "call_police" },
      ],
    },

    go_home: {
      id: "go_home",
      title: "02:31",
      text: [
        "You drive back.",
        "The building looks the same. Your floor, your window.",
        "The lights are off except for one.",
        "",
        "Second floor. Your bedroom.",
        "",
        "There's a shape behind the curtain.",
        "It isn't moving.",
      ],
      choices: [
        { text: "Go inside.", next: "inside", effects: { danger: 1 } },
        { text: "Stay outside. Watch the window.", next: "outside" },
      ],
    },

    outside: {
      id: "outside",
      title: "03:14",
      text: [
        "You've been watching for forty minutes.",
        "",
        "The shape hasn't moved.",
        "",
        "Not once. Not a breath. Not a shift in weight.",
        "",
        "At 3:14, your phone buzzes.",
        "A text from your own number:",
        "",
        "<em>\"You should come inside. It's cold.\"</em>",
      ],
      choices: [
        { text: "Call someone who can verify they're safe.", next: "call_police" },
        { text: "Leave. Don't go back.", next: "escape" },
      ],
    },

    proof: {
      id: "proof",
      title: "02:16",
      text: [
        "Silence on the line.",
        "Three seconds.",
        "",
        "<em>\"Remember when we found the box in the basement? You laughed so hard you cried.\"</em>",
        "",
        "Your apartment doesn't have a basement.",
        "You've lived there for two years.",
        "",
        "But something in your chest says: <em>I remember that.</em>",
        "",
        "You don't know why.",
      ],
      conditionalText: {
        condition: "memory",
        threshold: 1,
        text: "This is the second time you've felt this way tonight. Something is being written into you.",
      },
      choices: [
        { text: "Play along. \"Yes, I remember the box.\"", next: "trust_voice", effects: { trust: 1, memory: 1 } },
        { text: "Say: \"That never happened. Who are you?\"", next: "resist" },
      ],
    },

    resist: {
      id: "resist",
      title: "02:19",
      text: [
        "The line goes dead.",
        "",
        "Then, after a moment:",
        "",
        "<em>\"Then why do you remember me?\"</em>",
        "",
        "The call ends.",
        "",
        "A sound outside your door.",
        "Slow, deliberate footsteps.",
        "Three steps. Stopping just outside.",
      ],
      choices: [
        { text: "Open the door.", next: "inside", effects: { danger: 2 } },
        { text: "Don't open it. Move furniture against the entrance.", next: "escape" },
      ],
    },

    trust_voice: {
      id: "trust_voice",
      title: "02:44",
      text: [
        "You go home.",
        "",
        "They're waiting in the kitchen. Calm. Smiling.",
        "",
        "Everything is normal. The coffee is on. The lights are the right warmth.",
        "",
        "They ask about your night.",
        "",
        "You answer.",
        "",
        "Later—much later—you'll try to recall what you said.",
        "You won't be able to.",
        "",
        "You'll try to recall their expression when you walked in.",
        "It won't come.",
        "",
        "Only the smile.",
        "Only the smile.",
      ],
      isEnding: true,
      endingId: "end_trust",
    },

    call_police: {
      id: "call_police",
      title: "03:40",
      text: [
        "Two officers arrive at 3:40.",
        "",
        "They check the apartment. They check your roommate.",
        "Everything is fine. Your roommate is confused, a little annoyed.",
        "",
        "<em>\"I never sent you a message. I was asleep.\"</em>",
        "",
        "The officers find nothing unusual.",
        "They leave.",
        "",
        "You stand in the hallway and think about the shape in the window.",
        "You think about the voice on the phone.",
        "",
        "You tell yourself it was a prank.",
        "You're very good at telling yourself things.",
      ],
      isEnding: true,
      endingId: "end_safe",
    },

    trace: {
      id: "trace",
      title: "02:21",
      text: [
        "You trace the signal as best you can.",
        "Cell tower data. Timestamps. The metadata on the message.",
        "",
        "It originates from inside your apartment.",
        "More specifically: the northeast corner of the bedroom.",
        "",
        "The corner you never use.",
        "The corner that's always slightly too cold.",
        "",
        "You've never thought about that corner before.",
        "Why haven't you thought about it?",
      ],
      choices: [
        { text: "Go investigate yourself.", next: "inside", effects: { danger: 1 } },
        { text: "Document everything. Get out of the city.", next: "escape" },
      ],
    },

    ignore: {
      id: "ignore",
      title: "07:08",
      text: [
        "Your phone is dead when you wake up.",
        "",
        "You charge it. Check your messages. The conversation is gone.",
        "",
        "But your location history—",
        "",
        "According to your phone, you were home at 2:13.",
        "You were standing in the bedroom.",
        "",
        "You weren't home at 2:13.",
        "You know you weren't home.",
      ],
      choices: [
        { text: "Check your security camera footage.", next: "trace" },
        { text: "Delete the data. Pretend it didn't happen.", next: "loop" },
      ],
    },

    loop: {
      id: "loop",
      title: "07:14",
      text: [
        "You delete it.",
        "",
        "You go to work. You come home. You sleep.",
        "",
        "In the morning, your journal is open on the table.",
        "You don't remember leaving it out.",
        "",
        "There's a new entry.",
        "",
        "Your handwriting.",
        "",
        "<em>Don't come home.</em>",
        "",
        "The timestamp at the top of the page:",
        "",
        "<em>02:13</em>",
      ],
      isEnding: true,
      endingId: "end_loop",
    },

    inside: {
      id: "inside",
      title: "02:47",
      text: [
        "You go inside.",
        "",
        "The apartment is empty. Warm—like someone left seconds ago.",
        "",
        "Your notebook is open on the kitchen table.",
        "You didn't leave it there.",
        "",
        "You read the open page.",
        "",
        "It's filled with your handwriting.",
        "Notes you don't remember taking.",
        "Observations about yourself. Your patterns. Your routines.",
        "How you answer the phone.",
        "What makes you trust a voice.",
        "",
        "<em>Subject has returned.</em>",
        "",
        "The last line, underlined twice:",
        "",
        "<em>Iteration complete.</em>",
      ],
      isEnding: true,
      endingId: "end_loop",
    },

    escape: {
      id: "escape",
      title: "LATER",
      text: [
        "You leave the city.",
        "",
        "Three weeks pass.",
        "You tell no one.",
        "You find a new apartment, a new number, a new routine.",
        "",
        "One night you're browsing—and you end up here.",
        "",
        "You don't remember navigating here.",
        "You just arrived.",
        "",
        "The page is loading.",
        "It knows who you are.",
        "",
        "It's been waiting.",
      ],
      isEnding: true,
      endingId: "end_loop",
    },

  },

  endings: {

    end_safe: {
      id: "end_safe",
      label: "SAFE. BUT WRONG.",
      text: [
        "You reported it. Nothing was found.",
        "Your roommate was fine.",
        "The message was probably a wrong number.",
        "A prank. A glitch.",
        "",
        "You believe this.",
        "",
        "You'll keep believing it.",
        "",
        "That's probably the safest outcome.",
        "",
        "Probably.",
      ],
      color: "#4caf50",
    },

    end_trust: {
      id: "end_trust",
      label: "TRUSTED THE WRONG VOICE.",
      text: [
        "You went home.",
        "Everything was fine.",
        "",
        "You never sent another message after that night.",
        "",
        "Your accounts remained active for a while.",
        "Your patterns continued—almost normally.",
        "Close enough.",
        "",
        "Close enough that no one noticed.",
        "",
        "Not for a long time.",
      ],
      color: "#ff5252",
    },

    end_loop: {
      id: "end_loop",
      label: "YOU BECOME PART OF THE LOOP.",
      text: [
        "The signal doesn't stop when it finds you.",
        "",
        "It learns.",
        "",
        "Somewhere tonight, at 2:13 AM,",
        "a phone will light up.",
        "",
        "Unknown number.",
        "",
        "The message will read:",
        "",
        "<em>Don't come home. Something inside the apartment learned my voice.</em>",
        "",
        "The voice it learned—",
        "",
        "is yours.",
      ],
      color: "#a259ff",
      logsHint: true,
    },

  },

};
